travis:
  secure:
    BINSTAR_TOKEN: sxdiH9nrrCCvN16ueXgRJFH0ObwChY+ww4wia4TxIiChFjgtDANsxwphobzXU9vClfNPYFxuNNjXdR48POouOp8o31rXpy2UHRbYuAL9h01mocgOYpNDHYMrD09edv14kMbj2KQCKuEZVji05kux/eUuI3DghUhKoPgNOpHjtm8reVhAOMyc3UanY0wa/INCeRBsZCdSViIpquIOiBVC6QaLjVg0naRmTm9CX81M6CsWH7J6jn0oF5DEDlnSU3z8N/jJnKvyiRrennrSpUUsDMUXQ6xQg53K4kQTqEP06P1NLszut4d4P2DUP2SySDngMwGFKU8lZZxZzyo36fVYlt6DmRb3nRH8g5kpCYHEBwfktIrXpfhJhvh960jJ6YbHBkuAW/WtSriIaZv3h92RdJZpJ/vsOS2jxO+YU4aLvMtRsh8fU92mAgF4j7Sbcx6YCmWfQ0bsz/ur7qvoCv/Ct51Q0MWSxc/HNxAPwIGsT6KO6tNGzefo895PRh7vtk8y03pOGyXeAw3bOcccLmkuO4Mq0VEUIeU7mJ64gQMJy3EQRcbb3uUCEpjgtdYfh8ToV7OjUmND0Fcp2+JTb9woBsYzW5G0RKKFsqWymoo0zgTo3f4cq2IiCVdAVSdw7Oeu7SMY84Knn93/VCHlRoaVhnvDL+DvcUto/6OsCzr9DYI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
